/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gidas_comval_system;

import ClassAddresses.classIndicators;
import ClassAddresses.classInidicatorsGetset;
import static gidas_comval_system.Profile.s;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class indicators extends javax.swing.JFrame {

    classIndicators indicators = new classIndicators();
    
    public indicators() {
        initComponents();
        indicators.list_of_needs(cbo_basic_need);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbo_basic_need = new javax.swing.JComboBox<>();
        txt_desc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_basic_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("BASIC NEEDS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 77, -1, -1));

        jLabel3.setText("DESCRIPTION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 115, -1, -1));

        cbo_basic_need.setName(""); // NOI18N
        cbo_basic_need.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_basic_needItemStateChanged(evt);
            }
        });
        cbo_basic_need.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_basic_needActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_basic_need, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 74, 219, -1));
        getContentPane().add(txt_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 112, 219, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 180, 80, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("CANCEL");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, 40));

        lbl_basic_id.setText("jLabel4");
        getContentPane().add(lbl_basic_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 78, 50, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INDICATORS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
            classDb.dbconnect();
            
                 String timeString2="";
                  java.util.Date d2 = new java.util.Date();
                  SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
                  timeString2 = sdf2.format(d2);
                  String mm = timeString2;
                  String updated = "0000-00-00 00:00:00";
                  
        
        try {
            s =  classDb.conn.createStatement();
             s.executeUpdate("Insert INTO indicators(description,created_at,updated_at,basic_needs_id) "
                + "values('" + txt_desc.getText() + "','"+ mm +"'," 
                + "'"+ updated +"', "
                + "'"+ lbl_basic_id.getText()+"')");
            JOptionPane.showMessageDialog(null, "Save Record, Done.....", "Saving Record Notification", JOptionPane.INFORMATION_MESSAGE);

            s.close();
            classDb.conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(indicators.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbo_basic_needActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_basic_needActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_basic_needActionPerformed

    private void cbo_basic_needItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_basic_needItemStateChanged
        // TODO add your handling code here:
        
        
        classInidicatorsGetset d_vo = (classInidicatorsGetset)this.cbo_basic_need.getSelectedItem();
        int id_de = d_vo.getidneeds();
        String n = d_vo.getneeds();

        lbl_basic_id.setText(""+id_de);
     
        
        
    }//GEN-LAST:event_cbo_basic_needItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indicators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indicators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indicators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indicators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new indicators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_basic_need;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_basic_id;
    private javax.swing.JTextField txt_desc;
    // End of variables declaration//GEN-END:variables
}
